### ISSUE TITLE
404 received while setting up Travis

### ISSUE THREAD

**Issue by bdw429s** [elpete/cb-module-template#13]
This didn't happen the second time I tried to run it so I'm not sure if it was a transient error or something that happens to everyone the first time.  I figured I'm create this ticket in case anyone else ran into it so we'd know to look into it further.

Here's the full output of the command:
```
CommandBox:sandbox> module scaffold bradprivate "my private package"

Copying template over....

Installing dependencies....

Installing package [forgebox:coldbox@^4.3.0+188]

Installing package [forgebox:testbox@^2.4.0+80]

Setting up your Git repo....
Git repo initialized with an initial commit.

Creating GitHub repo....

I couldn't find a GitHub token for you.  Let's create one now!
Username: bdw429s
Password: *******************************
Token created!.

Repo created on Github.


I couldn't find a Travis token for you.  Creating one from your GitHub token now.
Token created!.

Syncing GitHub repos with Travis....
ERROR (@build.version@+@build.number@)

404 Not Found

D:\.Command Box\cfml\modules\cb-module-template\commands\module\scaffold.cfc: line 330
328:             // "MyClient/1.0.0" is used because Travis is bonkers with anything else
329:             cfhttpparam( type="header", name="User-Agent", value="MyClient/1.0.0" );
330:             cfhttpparam( type="header", name="Accept", value="application/vnd.travis-ci.2+json" );
331:         }
332:
called from D:\.Command Box\cfml\system\services\CommandService.cfc: line 303
301:                    // Run the command
302:                    try {
303:                            var result = commandInfo.commandReference.CFC.run( argumentCollection = parameterInfo.namedParameters );
304:                            lastCommandErrored = commandInfo.commandReference.CFC.hasError();
305:                    } catch( any e ){
called from D:\.Command Box\cfml\system\services\CommandService.cfc: line 133
131:            var commandChain = resolveCommand( line );
132:
133:            return runCommand( commandChain, line );
134:    }
135:
called from D:\.Command Box\cfml\system\Shell.cfc: line 479
477:                            }
478:                    } else {
479:                            var result = variables.commandService.runCommandLine( arguments.command );
480:                    }
481:
called from D:\.Command Box\cfml\system\Shell.cfc: line 428
426:                // If there's input, try to run it.
427:                            if( len( trim( line ) ) ) {
428:                                    callCommand( command=line, initialCommand=true );
429:                            }
430:
called from D:\.Command Box\cfml\system\Bootstrap.cfm: line 113
111:
112:            // Running the "reload" command will enter this while loop once
113:            while( shell.run( silent=silent ) ){
114:                    clearScreen = shell.getDoClearScreen();
115:
404 Not Found
        at lucee.runtime.tag.Http41._doEndTag(Http41.java:1265):1265
        at lucee.runtime.tag.Http41.doEndTag(Http41.java:636):636
        at lucee.runtime.tag.HttpImpl.doEndTag(HttpImpl.java:223):223
        at modules.cb_module_template585.commands.module.scaffold_cfc$cf.udfCall(/commandbox/modules/cb-module-template/commands/module/scaffold.cfc:330):33
0
        at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
        at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
        at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
        at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643
        at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
        at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
        at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1609):1609
        at system.services.commandservice_cfc$cf.udfCall1(/commandbox/system/services/CommandService.cfc:303):303
        at system.services.commandservice_cfc$cf.udfCall(/commandbox/system/services/CommandService.cfc):-1
        at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
        at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
        at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
        at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
        at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599):1599
        at system.services.commandservice_cfc$cf.udfCall1(/commandbox/system/services/CommandService.cfc:133):133
        at system.services.commandservice_cfc$cf.udfCall(/commandbox/system/services/CommandService.cfc):-1
        at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
        at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
        at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
        at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
        at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
        at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
        at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599):1599
        at system.shell_cfc$cf.udfCall3(/commandbox/system/Shell.cfc:479):479
        at system.shell_cfc$cf.udfCall(/commandbox/system/Shell.cfc):-1
        at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
        at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
        at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
        at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:775):775
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
        at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1609):1609
        at system.shell_cfc$cf.udfCall2(/commandbox/system/Shell.cfc:428):428
        at system.shell_cfc$cf.udfCall(/commandbox/system/Shell.cfc):-1
        at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
        at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
        at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
        at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643
        at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
        at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
        at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1609):1609
        at _command_box334.cfml.system.bootstrap_cfm$cf.call(/.Command Box/cfml/system/Bootstrap.cfm:113):113
        at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:957):957
        at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
        at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:225):225
        at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:37):37
        at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2271):2271
        at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2234):2234
        at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
        at lucee.runtime.engine.CFMLEngineImpl.cli(CFMLEngineImpl.java:760):760
        at lucee.loader.engine.CFMLEngineWrapper.cli(CFMLEngineWrapper.java:267):267
        at luceecli.CLIMain.run(CLIMain.java:223):223
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method):-2
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62):62
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43):43
        at java.lang.reflect.Method.invoke(Method.java:483):483
        at cliloader.LoaderCLIMain.execute(LoaderCLIMain.java:205):205
        at cliloader.LoaderCLIMain.main(LoaderCLIMain.java:699):699

```

**Comment by bdw429s** [comment]
I'm curious if there is some kind of caching going on that prevents Travis from seeing a new repo within a second of it being created.  The second time I ran this command (deleted the original repo and re-ran) it got past this step just fine.

**Comment by bdw429s** [comment]
This is worked around in the latest set of updates/pulls.
